package miscellaneous;

public class DynamicString 
{
	public static void main(String[] args) 
	{
		String url="https://www.google.com/search?q=selenium+java&rlz=1C1VDKB_enIN1012IN1012&sxsrf=AJOqlzVCQCYEwX7g_dJFbWH2yx090Pvkiw%3A1674476009069&ei=6XnOY6_4A7-N4-EPkayP4Aw&ved=0ahUKEwjvkNKd1d38AhW_xjgGHRHWA8wQ4dUDCA8&uact=5&oq=selenium+java&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCAAQgAQyBQgAEIAEMgUIABCABDILCAAQgAQQsQMQgwEyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6CAguELEDEIMBOhEILhCDARDHARCxAxDRAxCABDoRCC4QgAQQsQMQgwEQxwEQ0QM6BAguEEM6BAgAEEM6CgguELEDEIMBEEM6CwguEIMBELEDEIAEOggILhCDARCxAzoLCC4QgAQQsQMQgwE6DQguEIMBENQCELEDEEM6CgguEMcBENEDEEM6BwgAELEDEEM6CAgAEIAEELEDOgoILhCDARCxAxBDOgoIABCxAxCDARBDOgUIABCRAkoECEEYAEoECEYYAFAAWOMxYOQzaABwAXgAgAH5AYgB5A6SAQUwLjYuNJgBAKABAcABAQ&sclient=gws-wiz-serp";
		String[] s = url.split("\\+");

		
		
	}
	

}
